insert into USUARIO (ID,NOMBRE,ROL) values (1,'David','ADMINISTRADOR');
insert into USUARIO (ID,NOMBRE,ROL) values (2,'Eduardo','USUARIO');
insert into USUARIO (ID,NOMBRE,ROL) values (3,'Vanessa','USUARIO');
insert into SALA (ID,CAPACIDAD,NOMBRE) values (1,10,'Sala 1');
insert into RESERVA (ID,CAPACIDAD_RESERVADA,FECHA_INICIO,ESTADO_RESERVA,SALA_ID,USUARIO_ID) values (1,1,'2017-10-02 11:00:00','SOLICITADA',1,1);
insert into RESERVA (ID,CAPACIDAD_RESERVADA,FECHA_INICIO,ESTADO_RESERVA,SALA_ID,USUARIO_ID) values (2,1,'2017-10-02 10:00:00','CONFIRMADA',1,1);
insert into RESERVA (ID,CAPACIDAD_RESERVADA,FECHA_INICIO,ESTADO_RESERVA,SALA_ID,USUARIO_ID) values (3,1,'2017-10-02 11:00:00','SOLICITADA',1,2);
insert into RESERVA (ID,CAPACIDAD_RESERVADA,FECHA_INICIO,ESTADO_RESERVA,SALA_ID,USUARIO_ID) values (4,1,'2017-10-02 11:00:00','SOLICITADA',1,3);
insert into RESERVA (ID,CAPACIDAD_RESERVADA,FECHA_INICIO,ESTADO_RESERVA,SALA_ID,USUARIO_ID) values (5,1,'2017-10-02 09:00:00','SOLICITADA',1,3);